name: build
on:
  push:
    branches:
      - 'develop'
      - 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.ref_name }}
          context: .
          secrets: |
            "dot_env=${{ secrets.DOT_ENV_FILE }}"
            "version=${{ github.ref_name }}"
