name: 'build base'
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/warehouse-be-base:latest
          context: "{{defaultContext}}:runtime-base"
